HOST = "localhost"
PORT = 8000
DATABASE = "Schedulio.db"
MAIL_HOST = HOST
MAIL_PORT = PORT
MAIL_SENDER = "< 你的傳送信箱 >"
MAIL_SENDER_PASSWORD = "< 你的密碼 >"
MAIL_SEND_HOST = "< 信箱伺服器地址 > smtp.gmail.com"
MAIL_SEND_PORT = "< 連接埠 > port 465 (for SSL), or port 587 (for TLS)"
MAIL_TLS = "< 是否使用TLS > True/False"
MAIL_START_TLS = "< 是否啟動TLS,注意與MAIL_TLS衝突 >"
